name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        type:
          - Debug
          - Release

    name: Build ${{ matrix.type }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 设置 JDK
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: '19'
      - name: 设置缓存
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}
      - name: 配置签名
        run: |
          mkdir app/key
          echo ${{ secrets.KEY }} | base64 --decode >> app/key/scorer.jks
          echo ${{ secrets.PROPERTIES }} | base64 --decode >> app/key.properties
      - name: 编译 ${{ matrix.type }}
        run: |
          chmod +x ./gradlew
          ./gradlew assemble${{ matrix.type }}
      - name: 上传 APK
        uses: actions/upload-artifact@v3
        with:
          name: Scorer-Apk-${{ matrix.type }}
          path: app/build/outputs/apk/
      - name: 上传其他
        uses: actions/upload-artifact@v3
        with:
          name: Scorer-Other-${{ matrix.type }}
          path: |
            app/build/outputs/logs/
            app/build/outputs/mapping/
            app/build/outputs/sdk-dependencies/
